// Auto-generated by CRAFT Platform

// Validate and resolve network to ensure it's never an unexpected value.
// This prevents mismatches where env vars are partially injected.
const resolveNetwork = (raw: unknown): 'mainnet' | 'testnet' => {
  return raw === 'mainnet' ? 'mainnet' : 'testnet';
};

// Derive network-specific defaults so config.network and endpoints stay aligned.
const getNetworkDefaults = (network: 'mainnet' | 'testnet') => {
  const defaults = {
    mainnet: {
      horizonUrl: 'https://horizon.stellar.org',
      sorobanRpcUrl: 'https://soroban.stellar.org',
      networkPassphrase: 'Public Global Stellar Network ; September 2015',
    },
    testnet: {
      horizonUrl: 'https://horizon-testnet.stellar.org',
      sorobanRpcUrl: 'https://soroban-testnet.stellar.org',
      networkPassphrase: 'Test SDF Network ; September 2015',
    },
  };
  return defaults[network];
};

const network = resolveNetwork(process.env.NEXT_PUBLIC_STELLAR_NETWORK);
const networkDefaults = getNetworkDefaults(network);

export const config = {
    branding: {
        appName: process.env.NEXT_PUBLIC_APP_NAME || 'Soroban DeFi',
        primaryColor: process.env.NEXT_PUBLIC_PRIMARY_COLOR || '#4f9eff',
        secondaryColor: process.env.NEXT_PUBLIC_SECONDARY_COLOR || '#1a1f36',
    },
    stellar: {
        network,
        horizonUrl: process.env.NEXT_PUBLIC_HORIZON_URL || networkDefaults.horizonUrl,
        sorobanRpcUrl: process.env.NEXT_PUBLIC_SOROBAN_RPC_URL || networkDefaults.sorobanRpcUrl,
        networkPassphrase: process.env.NEXT_PUBLIC_NETWORK_PASSPHRASE || networkDefaults.networkPassphrase,
    },
    features: {
        enableCharts: process.env.NEXT_PUBLIC_ENABLE_CHARTS === 'true',
        enableTransactionHistory: process.env.NEXT_PUBLIC_ENABLE_TRANSACTION_HISTORY === 'true',
        enableAnalytics: process.env.NEXT_PUBLIC_ENABLE_ANALYTICS === 'true',
        enableNotifications: process.env.NEXT_PUBLIC_ENABLE_NOTIFICATIONS === 'true',
    },
    contracts: {
        // Contract addresses will be injected here
    },
} as const;

export default config;
